/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: junior.phillip (https://sketchfab.com/junior.phillip)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eth-coin-e6bd61ef2fa54308ba0ef65507ead9c9
Title: ETH Coin
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three';

export default function Eth(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/eth_coin.glb')
    const { actions } = useAnimations(animations, group)
    const goldenColor = new THREE.Color(0xCDAA00); // Gold color

  // Update the material color
    materials['Material.001'].color = goldenColor;
    
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cone_2" position={[0, 2.59, 0]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials['Material.001']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eth_coin.glb')
